package com.uaa.registroempleados.ui.theme

import androidx.compose.ui.graphics.Color

/*
 * Paleta generada con Material Design Theme Builder
 * (https://material-foundation.github.io/material-theme-builder/)
 * Color semilla: #00696D (verde azulado)
 */

// Esquema claro
val primaryLight = Color(0xFF00696D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9CF0F4)
val onPrimaryContainerLight = Color(0xFF002021)
val secondaryLight = Color(0xFF4A6364)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E9)
val onSecondaryContainerLight = Color(0xFF041F21)
val tertiaryLight = Color(0xFF4E5F7D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD6E3FF)
val onTertiaryContainerLight = Color(0xFF081C36)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF4FAFA)
val onBackgroundLight = Color(0xFF161D1D)
val surfaceLight = Color(0xFFF4FAFA)
val onSurfaceLight = Color(0xFF161D1D)
val surfaceVariantLight = Color(0xFFDAE4E5)
val onSurfaceVariantLight = Color(0xFF3F4849)
val outlineLight = Color(0xFF6F7979)
val outlineVariantLight = Color(0xFFBEC8C9)
val surfaceContainerLight = Color(0xFFE8EEEF)
val surfaceContainerHighLight = Color(0xFFE3E9E9)

// Esquema oscuro
val primaryDark = Color(0xFF80D4D8)
val onPrimaryDark = Color(0xFF003739)
val primaryContainerDark = Color(0xFF004F52)
val onPrimaryContainerDark = Color(0xFF9CF0F4)
val secondaryDark = Color(0xFFB1CCCD)
val onSecondaryDark = Color(0xFF1B3436)
val secondaryContainerDark = Color(0xFF324B4C)
val onSecondaryContainerDark = Color(0xFFCCE8E9)
val tertiaryDark = Color(0xFFB6C7EA)
val onTertiaryDark = Color(0xFF1F314C)
val tertiaryContainerDark = Color(0xFF364764)
val onTertiaryContainerDark = Color(0xFFD6E3FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1415)
val onBackgroundDark = Color(0xFFDDE4E4)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDDE4E4)
val surfaceVariantDark = Color(0xFF3F4849)
val onSurfaceVariantDark = Color(0xFFBEC8C9)
val outlineDark = Color(0xFF899393)
val outlineVariantDark = Color(0xFF3F4849)
val surfaceContainerDark = Color(0xFF1A2121)
val surfaceContainerHighDark = Color(0xFF252B2C)
